// Generated by apps/wolfensvelte/gen-assets.ts — do not edit.

/** Both atlases are 512x512: 8x8 cells of 64x64. */
export const ATLAS_SIZE = 512;
export const ATLAS_COLS = 8;
export const CELL_SIZE = 64;

export const WALL_ATLAS = "art/wall-atlas.png";
export const SPRITE_ATLAS = "art/sprite-atlas.png";

/** Wall texture id -> light-face cell; the dark face is the next cell. */
export const WALL_CELL: Readonly<Record<number, number>> = {
  1: 0,
  3: 2,
  5: 4,
  7: 6,
  9: 8,
  11: 10,
  13: 12,
  15: 14,
  17: 16,
  19: 18,
  21: 20,
  23: 22,
  25: 24,
  41: 26,
  99: 28,
  103: 30,
  107: 32,
  109: 34,
};

export const ELEVATOR_OFF_CELL = 32;
export const ELEVATOR_ON_CELL = 34;

/** Object texture id -> sprite atlas cell. */
export const OBJECT_CELL: Readonly<Record<number, number>> = {
  117: 0,
  118: 1,
  119: 2,
  120: 3,
  121: 4,
  123: 5,
  125: 6,
  126: 7,
  128: 8,
  129: 9,
  130: 10,
  131: 11,
  133: 12,
  136: 13,
  140: 14,
  141: 15,
  142: 16,
  143: 17,
  144: 18,
  146: 19,
  147: 20,
  148: 21,
  152: 22,
  153: 23,
  156: 24,
  159: 25,
  165: 26,
};

/** First of the 13 guard frames (Enemy.svelte keyframes: 0 idle, 1-4 walk, 5-8 dying, 9 hurt, 10 corpse, 11-12 attack). */
export const GUARD_CELL0 = 27;
/** First of the 12 dog cells, row-major over the 3-wide sheet: cell = DOG_CELL0 + row * 3 + col. */
export const DOG_CELL0 = 40;
export const DOG_SHEET_COLS = 3;
